#!/bin/bash
# Copyright (c) 2015, Daniele Viganò (daniele@vigano.me)
#
# systemd-query is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# systemd-query is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with systemd-query. If not, see <http://www.gnu.org/licenses/>.

# Requires BASH >= 4.0
if [ $BASH_VERSINFO -lt 4 ];
then
    echo "Error: BASH >= 4.0 is required."
    exit 1
fi

list() {
    command="systemctl list-unit-files --type=service"

    case $1 in
    'enabled' | 'disabled')
        $command | grep $1 | less;;
    '?')
        echo "Usage: $0 list [enabled | disabled | all]"
        exit 1;;
    * | 'all')
        $command;;
    esac
}

onoff() {
    command="systemctl -q $1 $2.service"

    if [ -n "$2" ];
    then
        $command
        if [ $? -eq 0  ] || [ "$1" = "status" ];
        then
            echo -e "[ \e[01;32mOK\e[0m ]\t${1^} service $2"
        else
            echo -e "[ \e[01;31m!!\e[0m ]\tSomenthing went wrong. Cannot $1 service $2"
            exit 1
        fi
    else
        echo -e "Usage: $0 <start | stop | restart | status> \e[01;31mservice\e[0m"
        exit 1
    fi
}

case $1 in
list)
    list $2;;
enable | disable | start | stop | restart | status)
    onoff $1 $2;;
*)
    echo "Usage: $0 <list [enabled | disabled | all ] | enable <service> | disable <service> | start <service> | stop <service> | restart <service> | status <service>>";;
esac
exit 0
